src/main/java/com/fisa/land/fisaland/User.java

feat:User Entity 추가 #1

---

src/main/java/com/fisa/land/fisaland/common/User.java
src/main/java/com/fisa/land/fisaland/common/controller/UserController.java

feat: Add User Controller #1

---

src/main/java/com/example/rentalsystem/entity/LendingRecords.java
src/main/java/com/example/rentalsystem/entity/LendingReviews.java
src/main/java/com/fisa/fisaland/lending/controller/LendingController.java
src/main/java/com/fisa/fisaland/lending/controller/ProductController.java
src/main/java/com/fisa/fisaland/lending/dto/LendingRequestDto.java
src/main/java/com/fisa/fisaland/lending/dto/ReturnRequestDto.java
src/main/java/com/fisa/fisaland/lending/entity/LendingRecordInfo.java
src/main/java/com/fisa/fisaland/lending/entity/LendingRecords.java
src/main/java/com/fisa/fisaland/lending/entity/Product.java
src/main/java/com/fisa/fisaland/lending/exception/CustomException.java
src/main/java/com/fisa/fisaland/lending/repository/LendingRecordInfoRepository.java
src/main/java/com/fisa/fisaland/lending/repository/LendingRecordsRepository.java
src/main/java/com/fisa/fisaland/lending/repository/ProductRepository.java
src/main/java/com/fisa/fisaland/lending/service/LendingService.java
src/main/java/com/fisa/fisaland/lending/service/ProductService.java
src/main/resources/static/products.html

ProuctList 구현 및 LendingRecord 제작ing

lending : Prouctlist&LendingRecord

---

src/main/java/com/fisa/fisaland/lending/entity/LendingRecordInfo.java
src/main/java/com/fisa/fisaland/lending/entity/LendingRecords.java
src/main/java/com/fisa/fisaland/lending/service/LendingService.java
src/main/resources/static/index.html

lending : Service Error 해결

---

src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
src/main/java/com/fisa/land/fisaland/common/dto/request/LoginDTO.java
src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java
src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java
src/main/java/com/fisa/land/fisaland/common/entity/User.java
src/main/java/com/fisa/land/fisaland/common/respository/UserRepository.java
src/main/java/com/fisa/land/fisaland/common/service/UserService.java
src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java

- 유저 정보 조회 기능 추가
- 유저 정보 수정 기능 추가

feat: 유저 조회, 수정 기능 추가 issue: #1

---

src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java
src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java
src/main/java/com/fisa/land/fisaland/common/entity/BaseTimeEntity.java
src/main/java/com/fisa/land/fisaland/common/entity/User.java
src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java
src/main/java/com/fisa/land/fisaland/market/entity/Market.java
src/main/java/com/fisa/land/fisaland/market/entity/MarketReview.java

- 사용자 활동 상태 컬럼 추가
- 사용자 삭제 기능 구현
- #1

feat: 사용자 활동 상태 컬럼 추가 및 사용자 삭제 기능 구현

---

src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
src/main/java/com/fisa/land/fisaland/common/dto/request/LoginDTO.java
src/main/java/com/fisa/land/fisaland/common/dto/request/UserDTO.java

docs: 사용자 API - 스웨거 설정 추가

---

src/main/java/com/fisa/land/fisaland/common/entity/Product.java
src/main/java/com/fisa/land/fisaland/common/exception/BusinessLoginException.java
src/main/java/com/fisa/land/fisaland/common/exception/ExceptionList.java
src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java

- 예외처리 handler 코드 작성
- 기존 코드 람다식 구성으로 수정
- #1 
- close #1

refactor: 예외 처리 및 람다식으로 수정

---

src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
src/main/java/com/fisa/land/fisaland/lending/dto/ProductDTO.java
src/main/java/com/fisa/land/fisaland/lending/entity/Product.java
src/main/java/com/fisa/land/fisaland/lending/repository/ProductRepository.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductService.java

feat: 상품등록 기능 추가

---

src/main/java/com/fisa/land/fisaland/lending/entity/Product.java

fix : Product 네이밍 수정

---

src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordInfoDto.java
src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordsDto.java
src/main/java/com/fisa/land/fisaland/lending/dto/LendingReviewsDto.java
src/main/java/com/fisa/land/fisaland/lending/entity/LendingRecordInfo.java
src/main/java/com/fisa/land/fisaland/lending/entity/LendingRecords.java
src/main/java/com/fisa/land/fisaland/lending/entity/LendingReviews.java
src/main/java/com/fisa/land/fisaland/lending/entity/Product.java
src/main/java/com/fisa/land/fisaland/lending/repository/LendingRecordInfoRepository.java
src/main/java/com/fisa/land/fisaland/lending/repository/LendingRecordsRepository.java
src/main/java/com/fisa/land/fisaland/lending/repository/LendingReviewsRepository.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingReviewsService.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingReviewsServiceImpl.java

fix: 리뷰CRUD 버그수정..

---

src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductService.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java

물건 반납승인시 유저ID 비교 추가, 대여신청 시 상태가 RENTED 이면 대여 불가하게 수정

Product 반납, 대여 조건 추가

---

src/main/java/com/fisa/land/fisaland/common/entity/User.java
src/main/java/com/fisa/land/fisaland/common/service/UserServiceImpl.java

fix:유저 정보 업데이트 시 수정시간 업데이트

---

src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
src/main/java/com/fisa/land/fisaland/lending/dto/ProductDTO.java
src/main/java/com/fisa/land/fisaland/lending/repository/ProductRepository.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductService.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java

feat: 내가 올른 물건 조회, 물건 삭제 기능 추가

---

src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingReviewsService.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingReviewsServiceImpl.java

feat: 평점 평균 보여주기

---

src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java

fix: 로그인 성공 시 userId 추가

---

src/main/java/com/fisa/land/fisaland/common/dto/response/UserResponseDTO.java
src/main/java/com/fisa/land/fisaland/page/MainPageController.java
src/main/resources/templates/myGathering.html

FEAT: 내가 만든 모임 view

---

src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
src/main/java/com/fisa/land/fisaland/lending/dto/LendingRecordStatusUpdateDto.java
src/main/java/com/fisa/land/fisaland/lending/entity/LendingRecordInfo.java
src/main/java/com/fisa/land/fisaland/lending/repository/LendingRecordRepository.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordService.java
src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java

feat: 대여 관련 CRUD

---

src/main/resources/templates/gathering_register.html

feat: gathering_register

---

src/main/java/com/fisa/land/fisaland/page/MainPageController.java
src/main/resources/templates/myBorrow.html
src/main/resources/templates/myLend.html

feat: myBorrow, myLend 페이지

---

build.gradle
src/main/java/com/fisa/land/fisaland/page/MainPageController.java
src/main/resources/templates/lending.html

feat: 빌리기 페이지

---

src/main/java/com/fisa/land/fisaland/page/MainPageController.java

fix: pageController 에러 해결

---

src/main/java/com/fisa/land/fisaland/page/MainPageController.java
src/main/resources/templates/marketReview.html

fix:PageController 에러 수정

---

src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java

fix: 대여 신청시 상품 상태 업데이트

---

src/main/java/com/fisa/land/fisaland/lending/service/LendingRecordServiceImpl.java

fix: 반납 신청 시 product 상태 변경

---

src/main/resources/templates/marketReview.html

- `market_review` 페이지 평균 평점 기능 추가
- `market_review` 페이지 버튼 위치 조정

refactor: marketReview page refactoring

---

src/main/java/com/fisa/land/fisaland/page/MainPageController.java
src/main/resources/templates/addProduct.html
src/main/resources/templates/myLend.html
src/main/resources/templates/myProducts.html

myLend, myBorrow, addProduct, myProducts html 추가

feat: myLend, myBorrow, addProduct, myProducts html 추가

---

src/main/java/com/fisa/land/fisaland/lending/dto/ProductDTO.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java
src/main/resources/templates/villageMain.html

fix: Vilage 페이지 수정중

---

src/main/java/com/fisa/land/fisaland/lending/entity/LendingReviews.java
src/main/resources/templates/myLend.html

fix: 물건 반납 로직 수정

---

src/main/resources/templates/myProducts.html

myProduct에서 productName 안보이던 오류 수정

fix: myProduct에서 productName 안보이던 오류 수정

---

build.gradle
src/main/java/com/fisa/land/fisaland/common/aspect/UserAspect.java
src/main/java/com/fisa/land/fisaland/common/controller/UserController.java
src/main/java/com/fisa/land/fisaland/lending/aspect/ErrorAspect.java
src/main/java/com/fisa/land/fisaland/lending/aspect/LendingAspect.java
src/main/java/com/fisa/land/fisaland/lending/aspect/OverdueAspect.java
src/main/java/com/fisa/land/fisaland/lending/aspect/ReviewAspect.java
src/main/java/com/fisa/land/fisaland/lending/aspect/UserActivityAspect.java
src/main/java/com/fisa/land/fisaland/lending/controller/LendingRecordController.java
src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java
src/main/java/com/fisa/land/fisaland/lending/controller/ProductController.java
src/main/resources/log4j.properties

feat: AOP Common, Village 로그추출기능 추가

---

src/main/java/com/fisa/land/fisaland/common/dto/request/LoginDTO.java
src/main/java/com/fisa/land/fisaland/lending/controller/LendingReviewsController.java

fix: 사용자 pw 로그 추출되는 버그 해결

---

src/main/resources/templates/myLend.html

myLend.html overdue fee 안 표시되던 오류 수정

fix: myLend.html overdue fee 안 표시되던 오류 수정

---

src/main/resources/static/assets/css/main2.css
src/main/resources/templates/villageMain.html

feat: villageMain 수정

---

src/main/resources/templates/login.html

refactor: 로그인 버튼 텍스트 위치 조정

---

src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordController.java

feat: AOP 피사에탑 로그 추출기능 생성

---

src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordController.java
src/main/java/com/fisa/land/fisaland/market/controller/GatheringRecordInfoController.java
src/main/java/com/fisa/land/fisaland/market/controller/MarketController.java
src/main/java/com/fisa/land/fisaland/market/controller/MarketReviewController.java
src/main/java/com/fisa/land/fisaland/market/dto/GatheringRecordDTO.java

fix: Market AOP 버그 수정완료

---

src/main/java/com/fisa/land/fisaland/lending/dto/ProductDTO.java
src/main/java/com/fisa/land/fisaland/lending/entity/Product.java
src/main/java/com/fisa/land/fisaland/lending/repository/ProductRepository.java
src/main/java/com/fisa/land/fisaland/lending/service/ProductServiceImpl.java
src/main/resources/templates/addProduct.html
src/main/resources/templates/create_gathering.html
src/main/resources/templates/myBorrow.html
src/main/resources/templates/myLend.html
src/main/resources/templates/myProducts.html
src/main/resources/templates/productReview.html
src/main/resources/templates/villageMain.html

Product 엔티티명 수정

---

src/main/java/com/fisa/land/fisaland/common/config/SecurityConfig.java

fix: 스웨거 문서 시큐리티 인증 제외
